/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 watch.gltf --transform 
Files: watch.gltf [374.28KB] > watch-transformed.glb [314.71KB] (16%)
Author: Dinesh Naidu (https://sketchfab.com/Dinesh_TS)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wrist-watch-cd471b55a205468ba87a2e8494a99746
Title: Wrist Watch
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Watch(props) {
  const { nodes, materials } = useGLTF('/watch-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.FB_IMG_15851297372435228} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.bodychains} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.bodymain} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.nutstwo} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/watch-transformed.glb')
